version: "3.8"
services:
  java_db:
    platform: linux/x86_64
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cotizacion
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - springboot-mysql-net

  java_app:
    build:
      context: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - java_db
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
